name: Java CI with Maven
#手动触发
on: workflow_dispatch

jobs:
  build:
#	配置权限
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      VERSION: $(mvn help:evaluate -Dexpression=version -q -DforceStdout)
    steps:
    - run: echo $VERSION
    
