name: Java CI with Maven
#手动触发
on: workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Get Maven Project Version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=version -q -DforceStdout)
          echo "Maven Project Version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Use Maven Project Version
        run: |
          echo "Using Maven Project Version from environment: $VERSION"

    
