name: Java CI with Maven
#手动触发
on: workflow_dispatch

jobs:
  build:
#	配置权限
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
# 下载代码
    - uses: actions/checkout@v3
    - name: Set up JDK 1
# 安装 JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
# Maven 打包 
    - name: Build with Maven
      run: mvn -B package --file pom.xml


 # 获取版本号
    - name: Get Version
      id: get_version
      run: echo "::set-output name=VERSION::$(mvn help:evaluate -Dexpression=version -q -DforceStdout)"

# 将打包好的 Jar 包 放到 staging 文件夹
    - run: mkdir staging && cp target/*.war staging


# 上传文件并发布 Release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.get_version.outputs.VERSION }}"
        prerelease: false
        title: "Release ${{ steps.get_version.outputs.VERSION }}"
        files: |
          staging/*.war         
