name: Java CI with Maven
#手动触发
on: workflow_dispatch

jobs:
  build:
#	配置权限
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - run: "$GITHUB_ENV.RELEASE_VERSION"    
    
