name: Java CI with Maven
#手动触发
on: workflow_dispatch

jobs:
  build:
#	配置权限
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
       - name: Get version
         id: get_version
         run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
       - run: ${{ steps.get_version.outputs.VERSION }}  
    
